# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.Category'),
        ),
    ]
